server:
  port: 8081
  error:
    include-stacktrace: never

feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 3000
        loggerLevel: basic

logging:
  level:
    com:
      projects:
        openfeignPOC: DEBUG